name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.ACTIONS }}
        BRANCH: gh-pages
        FOLDER: storybook-static
        BUILD_SCRIPT: npm install && npm run build-storybook